name: Install Dependencies with UV

on:
  pull_request:
  push:
    branches: [main, master]


jobs:
  install:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install uv
        uses: astral-sh/setup-uv@v4

      - name: Create virtual environment
        run: |
          uv venv

      - name: Install dependencies with uv
        run: |
          uv pip install --no-cache-dir  -r requirements.txt

      - name: Install marimo
        run: |
          uv pip install --no-cache-dir  marimo

      - name: Convert notebooks to HTML
        run: |
          mkdir -p html_exports
          find . -name "*.ipynb" -not -path "./html_exports/*" -exec sh -c '
            for notebook do
              echo "Converting $notebook..."
              filename=$(basename "$notebook" .ipynb)
              marimo export --format html "$notebook" --output "html_exports/${filename}.html" || echo "Failed to convert $notebook"
            done
          ' sh {} +
