name: Pre-commit Checks

on:
  pull_request:
  push:
    branches: [main, master]

jobs:
  pre-commit:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: run pre-commit
        uses: pre-commit/action@v3.0.1
        with:
          extra_args: '--verbose --all-files --color always --show-diff-on-failure'
